name: GHCR Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup ${{ matrix.package }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - trakt-toggl-sync
          - docker-bitlbee
          - docker-stunnel
          - reddit-rss-fetcher
          - day-of-year-calendar
          - sunrise-sunset-calendar
    steps:
      - name: Delete untagged and old versions
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ matrix.package }}
          keep-n-tagged: 5
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
          exclude-tags: latest,main
