name: Test Secrets

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "has username=${{ secrets.DOCKER_USERNAME != '' }}"
