name: Test Self Call

on:
  workflow_dispatch:

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/docker-build-scan-push.yml@main
    with:
      image_name: test-image
      enable_integration_test: false
      enable_release_drafter: false
    secrets: inherit
