name: Test Inputs In If

on:
  workflow_call:
    inputs:
      enable_scan:
        type: boolean
        required: false
        default: true

jobs:
  scan:
    runs-on: ubuntu-latest
    if: inputs.enable_scan
    steps:
      - run: echo "scanning"
